import test from 'node:test'; import assert from 'node:assert/strict';
import { evaluateHoldem, evaluateOmaha, madeHandCards, resolveHoldem } from '../src/texasholdem.ts'; import type { Card, Rank, Suit } from '../src/blackjack.ts';
const cards=(values:Array<[Rank,Suit]>):Card[]=>values.map(([rank,suit],i)=>({id:`${suit}-${rank}-${i}`,rank,suit}));
test('7장 중 가장 높은 홀덤 족보를 선택한다',()=>{ assert.equal(evaluateHoldem(cards([['A','♠'],['K','♠'],['Q','♠'],['J','♠'],['10','♠'],['2','♥'],['3','♦']])).label,'로열 플러시'); });
test('플레이어와 상대의 승패를 판정한다',()=>{ const community=cards([['A','♠'],['K','♥'],['7','♦'],['4','♣'],['2','♠']]); const result=resolveHoldem(cards([['A','♥'],['A','♦']]),cards([['K','♠'],['K','♦']]),community); assert.equal(result.result,'win'); });
test('같은 보드 족보면 무승부다',()=>{ const community=cards([['10','♠'],['J','♥'],['Q','♦'],['K','♣'],['A','♠']]); assert.equal(resolveHoldem(cards([['2','♥'],['3','♦']]),cards([['4','♥'],['5','♦']]),community).result,'push'); });
test('오마하는 개인 카드 정확히 2장과 공용 카드 3장을 사용한다',()=>{ const hole=cards([['A','♠'],['K','♠'],['2','♥'],['3','♦']]); const board=cards([['Q','♠'],['J','♠'],['10','♠'],['9','♠'],['8','♠']]); assert.equal(evaluateOmaha(hole,board).label,'로열 플러시'); const noSpade=cards([['A','♥'],['K','♦'],['2','♥'],['3','♦']]); assert.notEqual(evaluateOmaha(noSpade,board).label,'스트레이트 플러시'); });
test('결과 카드는 족보가 바로 보이도록 정렬한다',()=>{ const fullHouse=evaluateHoldem(cards([['K','♠'],['8','♠'],['8','♥'],['K','♥'],['8','♦'],['2','♣'],['3','♣']])); assert.deepEqual(fullHouse.cards.map((card)=>card.rank),['8','8','8','K','K']); const straight=evaluateHoldem(cards([['10','♠'],['A','♠'],['Q','♥'],['J','♦'],['K','♣'],['2','♣'],['3','♣']])); assert.deepEqual(straight.cards.map((card)=>card.rank),['A','K','Q','J','10']); });
test('화면에는 족보를 만든 카드만 표시하고 키커는 제외한다',()=>{ const twoPair=evaluateHoldem(cards([['4','♠'],['4','♦'],['9','♣'],['9','♥'],['Q','♣'],['J','♥'],['2','♣']])); assert.deepEqual(madeHandCards(twoPair).map((card)=>card.rank),['9','9','4','4']); const pair=evaluateHoldem(cards([['9','♠'],['9','♦'],['Q','♣'],['J','♥'],['5','♣'],['3','♥'],['2','♣']])); assert.deepEqual(madeHandCards(pair).map((card)=>card.rank),['9','9']); });
